### ISSUE TITLE
ValueError: Locale [hr] does not exist.

### ISSUE THREAD

**Issue by gour** [dagraham/etm-dgraham#2]
Hello,

attempt to change `locale:` into `hr` results in:

``` 
 File "/home/gour/.virtualenvs/etm/lib64/python3.8/site-packages/pendulum/helpers.py", line 204, in set_locale
    locale(name)
  File "/home/gour/.virtualenvs/etm/lib64/python3.8/site-packages/pendulum/helpers.py", line 200, in locale
    return Locale.load(name)
  File "/home/gour/.virtualenvs/etm/lib64/python3.8/site-packages/pendulum/locales/locale.py", line 42, in load
    raise ValueError("Locale [{}] does not exist.".format(locale))
ValueError: Locale [hr] does not exist.
```

Any hint what I'm missing?

Sincerely,
Gour

**Comment by dagraham** [comment]
Locale is a bit of a mystery. `hr` should work for Croatian but doesn't. I'll see what I can figure out.

**Comment by dagraham** [comment]
Could you try the following?
From a prompt run
$ locale -a

For me, all  the items in the resulting list start with "en" so not much help for Croatian.
  
Then start a python interactive session 
$ python3
>>> import locale
>>> locale.setlocale(locale.LC_NUMERIC, <suspect>)

where <suspect> is an item from the list. For me, an example would be 
>>> locale.setlocale(locale.LC_NUMERIC, "en_NZ.utf8")

Let me know if you find one that works.

Your other two issues are fixed (I hope) in 4.5.2.

- Dan

**Comment by gour** [comment]
> Could you try the following?
> $ locale -a
>
> For me, all the items in the resulting list start with "en" so not much help for Croatian.

I've plenty of locales available and here is my `locale`:

```
$ locale
LANG=en_GB.utf8
LC_CTYPE=hr_HR.utf-8
LC_NUMERIC=hr_HR.utf-8
LC_TIME=hr_HR.utf-8
LC_COLLATE=hr_HR.utf-8
LC_MONETARY=hr_HR.UTF-8
LC_MESSAGES=en_GB.utf-8
LC_PAPER=hr_HR.UTF-8
LC_NAME=hr_HR.utf-8
LC_ADDRESS=hr_HR.utf-8
LC_TELEPHONE=hr_HR.utf-8
LC_MEASUREMENT=hr_HR.UTF-8
LC_IDENTIFICATION=hr_HR.utf-8
LC_ALL=
```

and here is output of another utility `localectl`:

```
 $  localectl status
   System Locale: LANG=en_GB.utf-8
                  LC_CTYPE=hr_HR.utf-8
                  LC_NUMERIC=hr_HR.utf-8
                  LC_TIME=hr_HR.utf-8
                  LC_COLLATE=hr_HR.utf-8
                  LC_NAME=hr_HR.utf-8
                  LC_ADDRESS=hr_HR.utf-8
                  LC_TELEPHONE=hr_HR.utf-8
                  LC_IDENTIFICATION=hr_HR.utf-8
       VC Keymap: hr
      X11 Layout: hr
```

As you can see I use combination of en_GB & hr_HR locales.

Now, back to the Python:

```
$  python3
Python 3.8.3 (default, May 15 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_NUMERIC, "hr_HR.utf8")
'hr_HR.utf8'
>>> locale.setlocale(locale.LC_NUMERIC, "en_GB.utf8")
'en_GB.utf8'
```

so, both are working, but, etm is still crashing...


Sincerely,
Gour

**Comment by dagraham** [comment]
This is partially fixed in 4.5.3. Unsupported locales will be allowed and  the failure reported in an error log message.

The locale "hr" will now work for calendar (the half-yearly calendar invoked by pressing y) and, generally, for the python locale setting. So far as I can tell, unfortunately, pendulum does not yet support "hr" so month and weekday names elsewhere will probably be in English.  I have requested that pendulum add support for "hr" (hr_HR: UTF-8).
